services:
  app:
    build: .
    volumes:
      - .:/home/node/app
      - /home/node/app/node_modules
    ports:
      - 3001:3001

  db:
    build: ./.docker/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    ports:
      - 27017:27017